@startuml
'https://plantuml.com/activity-diagram-beta

start
':ClickServlet.handleRequest();
':new page;
'if (Page.onSecurityCheck) then (true)
'  :Page.onInit();
'  if (isForward?) then (no)
'    :Process controls;
'    if (continue processing?) then (no)
'      stop
'    endif
'
'    if (isPost?) then (yes)
'      :Page.onPost();
'    else (no)
'      :Page.onGet();
'    endif
'    :Page.onRender();
'  endif
'else (false)
'endif
'
'if (do redirect?) then (yes)
'  :redirect process;
'else
'  if (do forward?) then (yes)
'    :Forward request;
'  else (no)
'    :Render page template;
'  endif
'endif

:接口调用;
:查询Redis;
if (缓存命中) then (true)
else (false)
  :查询数据库;
  if (查询命中) then (true)
    :写入缓存;
  else (false)
    :返回null值;
  endif
endif

:返回结果;

stop

@enduml
