server:
  port: 8888

spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3307/web?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6380
    password: password
    timeout: 3000

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity
#showSql
logging:
  level:
    com:
      example:
        mapper : debug
